-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookeventdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookeventdb` ;

-- -----------------------------------------------------
-- Schema bookeventdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookeventdb` DEFAULT CHARACTER SET utf8 ;
USE `bookeventdb` ;

-- -----------------------------------------------------
-- Table `bookeventdb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookeventdb`.`book` ;

CREATE TABLE IF NOT EXISTS `bookeventdb`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `series` VARCHAR(45) NULL,
  `description` VARCHAR(2000) NULL,
  `image_url` VARCHAR(500) NULL,
  `studied` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS admin@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';

GRANT SELECT, INSERT, TRIGGER ON TABLE `bookeventdb`.* TO 'admin'@'localhost';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `bookeventdb`.* TO 'admin'@'localhost';
GRANT ALL ON `bookeventdb`.* TO 'admin'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bookeventdb`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookeventdb`;
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (1, 'Harry Potter and the Sorcer\'s Stone', 'J.K. Rowling', 'Harry Potter', 'Harry Potter\'s life is miserable. His parents are dead and he\'s stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he\'s a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.\n\nAfter a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry.\n\nThough Harry\'s first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it\'s his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.\n\nFull of sympathetic characters, wildly imaginative situations, and countless exciting details, the first installment in the series assembles an unforgettable magical world and sets the stage for many high-stakes adventures to come.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474154022l/3._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (2, 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Harry Potter', 'Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.\n\nAnd strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474169725l/15881._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (3, 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Harry Potter', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.\n\nNow he has escaped, leaving only two clues as to where he might be headed: Harry Potter\'s defeat of You-Know-Who was Black\'s downfall as well. And the Azkaban guards heard Black muttering in his sleep, \"He\'s at Hogwarts . . . he\'s at Hogwarts.\"\n\nHarry Potter isn\'t safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630547330l/5._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (4, 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 'Harry Potter', 'Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that\'s supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn\'t happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he\'s not normal - even by wizarding standards.\n\nAnd in his case, different can be deadly.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554006152l/6.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (5, 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'Harry Potter', 'There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?\n\nHarry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.\n\nAs the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.\n\nHis fate depends on them all.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (6, 'Harry Potter and the Half Blood Prince', 'J.K. Rowling', 'Harry Potter', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.\n\nAnd yet . . .\n\nAs in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince.\n\nSo it\'s the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587697303l/1._SX318_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (7, 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 'Harry Potter', 'It\'s no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it\'s up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry\'s Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474171184l/136251._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (8, 'The Hunger Games', 'Suzanne Collins', 'The Hunger Games', 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.\n\nSixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister\'s place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (9, 'Catching Fire', 'Suzanne Collins', 'The Hunger Games', 'Sparks are igniting.\nFlames are spreading.\nAnd the Capitol wants revenge.\n\nAgainst all odds, Katniss Everdeen has won the Hunger Games. She and fellow District 12 tribute Peeta Mellark are miraculously still alive. Katniss should be relieved, happy even. After all, she has returned to her family and her longtime friend, Gale. Yet nothing is the way Katniss wishes it to be. Gale holds her at an icy distance. Peeta has turned his back on her completely. And there are whispers of a rebellion against the Capitol—a rebellion that Katniss and Peeta may have helped create.\n\nMuch to her shock, Katniss has fueled an unrest that she\'s afraid she cannot stop. And what scares her even more is that she\'s not entirely convinced she should try. As time draws near for Katniss and Peeta to visit the districts on the Capitol\'s cruel Victory Tour, the stakes are higher than ever. If they can\'t prove, without a shadow of a doubt, that they are lost in their love for each other, the consequences will be horrifying.\n\nIn Catching Fire, the second novel of the Hunger Games trilogy, Suzanne Collins continues the story of Katniss Everdeen, testing her more than ever before . . . and surprising readers at every turn.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722941l/6148028.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (10, 'Mockingjay', 'Suzanne Collins', 'The Hunger Games', 'My name is Katniss Everdeen.\nWhy am I not dead?\nI should be dead.\n\nKatniss Everdeen, girl on fire, has survived, even though her home has been destroyed. Gale has escaped. Katniss\'s family is safe. Peeta has been captured by the Capitol. District 13 really does exist. There are rebels. There are new leaders. A revolution is unfolding.\n\nIt is by design that Katniss was rescued from the arena in the cruel and haunting Quarter Quell, and it is by design that she has long been part of the revolution without knowing it. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Everyone, it seems, has had a hand in the carefully laid plans—except Katniss.\n\nThe success of the rebellion hinges on Katniss\'s willingness to be a pawn, to accept responsibility for countless lives, and to change the course of the future of Panem. To do this, she must put aside her feelings of anger and distrust. She must become the rebels\' Mockingjay—no matter what the personal cost.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722918l/7260188._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (11, 'The Ballad of Songbirds and Snakes', 'Suzanne Collins', 'The Hunger Games', 'It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capital, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The once-mighty house of Snow has fallen on hard times, its fate hanging on the slender chance that Coriolanus will be able to outcharm, outwit, and outmaneuver his fellow students to mentor the winning tribute.\n\nThe odds are against him. He\'s been given the humiliating assignment of mentoring the female tribute from District 12, the lowest of the low. Their fates are now completely intertwined -- every choice Coriolanus makes could lead to favor or failure, triumph or ruin. Inside the arena, it will be a fight to the death. Outside the arena, Coriolanus starts to feel for his doomed tribute... and must weigh his need to follow the rules against his desire to survive no matter what it takes.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1593892032l/51901147._SY475_.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (12, 'The Lightening Thief', 'Rick Riordan', 'Percy Jackson and the Olympians', 'Percy Jackson is a good kid, but he can\'t seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse - Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy\'s mom finds out, she knows it\'s time that he knew the truth about where he came from, and that he go to the one place he\'ll be safe. She sends Percy to Camp Half Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena - Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1400602609l/28187.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (13, 'The Sea of Monsters', 'Rick Riordan', 'Percy Jackson and the Olympians', 'The heroic son of Poseidon makes an action-packed comeback in the second must-read installment of Rick Riordan\'s amazing young readers series. Starring Percy Jackson, a \"half blood\" whose mother is human and whose father is the God of the Sea, Riordan\'s series combines cliffhanger adventure and Greek mythology lessons that results in true page-turners that get better with each installment.\n\nIn this episode, The Sea of Monsters, Percy sets out to retrieve the Golden Fleece before his summer camp is destroyed, surpassing the first book\'s drama and setting the stage for more thrills to come.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1400602661l/28186.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (14, 'The Titan\'s Curse', 'Rick Riordan', 'Percy Jackson and the Olympians', 'It\'s not everyday you find yourself in combat with a half-lion, half-human.\n\nBut when you\'re the son of a Greek god, it happens. And now my friend Annabeth is missing, a goddess is in chains and only five half-blood heroes can join the quest to defeat the doomsday monster.\n\nOh, and guess what? The Oracle has predicted that not all of us will survive...', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361038385l/561456.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (15, 'The Battle of the Labyrinth', 'Rick Riordan', 'Percy Jackson and the Olympians', 'Percy Jackson isn\'t expecting freshman orientation to be any fun. But when a mysterious mortal acquaintance appears at his potential new school, followed by demon cheerleaders, things quickly move from bad to worse.\n\nIn this fourth installment of the blockbuster series, time is running out as war between the Olympians and the evil Titan lord Kronos draws near. Even the safe haven of Camp Half-Blood grows more vulnerable by the minute as Kronos\'s army prepares to invade its once impenetrable borders. To stop the invasion, Percy and his demigod friends must set out on a quest through the Labyrinth - a sprawling underground world with stunning surprises at every turn.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1518607478l/2120932.jpg', 1);
INSERT INTO `bookeventdb`.`book` (`id`, `title`, `author`, `series`, `description`, `image_url`, `studied`) VALUES (16, 'The Last Olympian', 'Rick Riordan', 'Percy Jackson and the Olympians', 'All year the half-bloods have been preparing for battle against the Titans, knowing the odds of victory are grim. Kronos\'s army is stronger than ever, and with every god and half-blood he recruits, the evil Titan\'s power only grows.\n\nWhile the Olympians struggle to contain the rampaging monster Typhon, Kronos begins his advance on New York City, where Mount Olympus stands virtually unguarded. Now it\'s up to Percy Jackson and an army of young demigods to stop the Lord of Time.\n\nIn this momentous final book in the New York Times best-selling series, the long-awaited prophecy surrounding Percy\'s sixteenth birthday unfolds. And as the battle for Western civilization rages on the streets of Manhattan, Percy faces a terrifying suspicion that he may be fighting against his own fate.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1519022209l/4556058.jpg', 1);

COMMIT;

